name: Push React Artifact to JFrog

on:
  workflow_call:
    inputs:
      node_version:
        description: 'Node.js version to use'
        required: true
        type: string
      jfrog_artifact_path:
        description: 'The path where the artifact should be uploaded in JFrog'
        required: true
        type: string
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js with the version from input
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}

      # Step 3: Install JFrog CLI
      - name: Install JFrog CLI
        run: |
          curl -fL https://getcli.jfrog.io | sh
          chmod +x jfrog
          sudo mv jfrog /usr/local/bin/jfrog    

      # Step 4: Install npm dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Build the React project
      - name: Build React app
        run: npm run build

      # Step 6: Configure JFrog CLI using inputs
      - name: Configure JFrog CLI
        run: |
          jfrog rt config --url "${{ inputs.jfrog_url }}" \
                          --user "${{ inputs.jfrog_username }}" \
                          --apikey "${{ inputs.jfrog_api_key }}"  

      # Step 7: Upload the build output to JFrog Artifactory
      - name: Upload React artifact to JFrog Artifactory
        run: |
          jfrog rt u "build/*" "${{ inputs.jfrog_artifact_path }}/" --build-name=react-build --build-number=${{ github.run_id }}
